-- =============================================
-- MIGRACIONES PARA PRODUCCIÓN (Hostinger)
-- Ejecutar en phpMyAdmin de Hostinger
-- =============================================

-- 1. Tabla de avatares (si no existe)
CREATE TABLE IF NOT EXISTS `avatares_perfil` (
  `id_avatar` int(11) NOT NULL AUTO_INCREMENT,
  `imagen` varchar(255) NOT NULL,
  `activo` tinyint(1) NOT NULL DEFAULT 1,
  `creado` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id_avatar`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 1b. Fix: si la tabla ya existe con columna 'id', renombrarla a 'id_avatar'
-- (Ejecutar manualmente SOLO si la tabla ya fue creada con 'id')
-- ALTER TABLE `avatares_perfil` CHANGE COLUMN `id` `id_avatar` int(11) NOT NULL AUTO_INCREMENT;

-- 2. Columnas nuevas en usuarios (si no existen)
-- sexo (debe ir primero porque fecha_nacimiento lo referencia con AFTER)
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `sexo` enum('masculino','femenino','otro') DEFAULT NULL AFTER `correo`;

-- fecha_nacimiento
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `fecha_nacimiento` date DEFAULT NULL AFTER `sexo`;

-- entidad (ubicación)
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `entidad` varchar(3) DEFAULT NULL AFTER `fecha_nacimiento`;

-- avatar_id (referencia al avatar seleccionado)
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `avatar_id` int(11) DEFAULT NULL AFTER `entidad`;

-- 3. Tabla de lectores (usuarios públicos, separada de administradores)
CREATE TABLE IF NOT EXISTS `lectores` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  `usuario` varchar(100) NOT NULL,
  `correo` varchar(255) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `sexo` enum('masculino','femenino','otro') DEFAULT NULL,
  `fecha_nacimiento` date DEFAULT NULL,
  `entidad` varchar(3) DEFAULT NULL,
  `avatar_id` int(11) DEFAULT NULL,
  `creado` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_lectores_usuario` (`usuario`),
  UNIQUE KEY `uq_lectores_correo` (`correo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 4. Migrar lectores existentes de usuarios → lectores
--    (usuarios públicos = todos los perm_* en 0)
INSERT IGNORE INTO `lectores` (`nombre`, `usuario`, `correo`, `password_hash`, `sexo`, `fecha_nacimiento`, `entidad`, `avatar_id`, `creado`)
SELECT `nombre`, `usuario`, `correo`, `pass`, `sexo`, `fecha_nacimiento`, `entidad`, `avatar_id`, `registro`
FROM `usuarios`
WHERE `perm_categorias` = 0
  AND `perm_noticias` = 0
  AND `perm_publicidad` = 0
  AND `perm_suscripciones` = 0
  AND `perm_usuarios` = 0
  AND `perm_correos` = 0
  AND `perm_videos` = 0;

-- 5. Perfiles públicos de editores
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `biografia` TEXT DEFAULT NULL AFTER `avatar_id`;
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `foto_personal` VARCHAR(255) DEFAULT NULL AFTER `biografia`;
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `link_twitter` VARCHAR(255) DEFAULT NULL AFTER `foto_personal`;
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `link_instagram` VARCHAR(255) DEFAULT NULL AFTER `link_twitter`;

-- 7. Filtro de diccionario (palabras prohibidas)
CREATE TABLE IF NOT EXISTS `filtro_diccionario` (
  `id_palabra` int(11) NOT NULL AUTO_INCREMENT,
  `palabra_baneada` varchar(255) NOT NULL,
  `reemplazo` varchar(255) DEFAULT '***',
  PRIMARY KEY (`id_palabra`),
  UNIQUE KEY `uq_palabra` (`palabra_baneada`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 8. Configuración de comentarios por noticia
CREATE TABLE IF NOT EXISTS `config_comentarios` (
  `id_config` int(11) NOT NULL AUTO_INCREMENT,
  `noticia_id` int(11) NOT NULL,
  `permitir_comentarios` tinyint(1) NOT NULL DEFAULT 1,
  `moderacion_previa` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_config`),
  UNIQUE KEY `uq_config_noticia` (`noticia_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 9. Comentarios de lectores
CREATE TABLE IF NOT EXISTS `comentarios` (
  `id_comentario` int(11) NOT NULL AUTO_INCREMENT,
  `noticia_id` int(11) NOT NULL,
  `lector_id` int(11) NOT NULL,
  `contenido` text NOT NULL,
  `fecha_publicacion` timestamp NOT NULL DEFAULT current_timestamp(),
  `estado` enum('activo','oculto','eliminado') NOT NULL DEFAULT 'activo',
  PRIMARY KEY (`id_comentario`),
  KEY `idx_comentarios_noticia` (`noticia_id`),
  KEY `idx_comentarios_lector` (`lector_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 10. Historial de ediciones de comentarios
CREATE TABLE IF NOT EXISTS `historial_ediciones` (
  `id_edicion` int(11) NOT NULL AUTO_INCREMENT,
  `comentario_id` int(11) NOT NULL,
  `contenido_anterior` text NOT NULL,
  `fecha_edicion` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id_edicion`),
  KEY `idx_historial_comentario` (`comentario_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 11. Likes en comentarios
CREATE TABLE IF NOT EXISTS `likes_comentarios` (
  `id_like` int(11) NOT NULL AUTO_INCREMENT,
  `comentario_id` int(11) NOT NULL,
  `lector_id` int(11) NOT NULL,
  `fecha` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id_like`),
  UNIQUE KEY `uq_like_comentario_lector` (`comentario_id`, `lector_id`),
  KEY `idx_likes_comentario` (`comentario_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 12. Reportes de comentarios
CREATE TABLE IF NOT EXISTS `reportes_comentarios` (
  `id_reporte` int(11) NOT NULL AUTO_INCREMENT,
  `comentario_id` int(11) NOT NULL,
  `lector_id` int(11) NOT NULL,
  `motivo` varchar(255) NOT NULL,
  `fecha` timestamp NOT NULL DEFAULT current_timestamp(),
  `estatus` enum('pendiente','revisado','descartado') NOT NULL DEFAULT 'pendiente',
  PRIMARY KEY (`id_reporte`),
  KEY `idx_reportes_comentario` (`comentario_id`),
  KEY `idx_reportes_lector` (`lector_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 13. Soporte para comentarios de admins/editores
ALTER TABLE `comentarios` MODIFY `lector_id` int(11) DEFAULT NULL;
ALTER TABLE `comentarios` ADD COLUMN IF NOT EXISTS `usuario_id` int(11) DEFAULT NULL AFTER `lector_id`;

-- 14. (OPCIONAL) Eliminar lectores migrados de la tabla usuarios
--    Descomenta SOLO después de verificar que la migración fue correcta
-- DELETE FROM `usuarios`
-- WHERE `perm_categorias` = 0
--   AND `perm_noticias` = 0
--   AND `perm_publicidad` = 0
--   AND `perm_suscripciones` = 0
--   AND `perm_usuarios` = 0
--   AND `perm_correos` = 0
--   AND `perm_videos` = 0;

-- 15. Auditoría de noticias (rastrear quién creó y editó)
ALTER TABLE `noticias` ADD COLUMN IF NOT EXISTS `creado_por` INT NULL AFTER `fecha_publicacion`;
ALTER TABLE `noticias` ADD COLUMN IF NOT EXISTS `editado_por` INT NULL AFTER `creado_por`;
ALTER TABLE `noticias` ADD COLUMN IF NOT EXISTS `ultima_edicion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `editado_por`;

-- Foreign keys para auditoría
ALTER TABLE `noticias` ADD CONSTRAINT IF NOT EXISTS `fk_noticias_creado_por` FOREIGN KEY (`creado_por`) REFERENCES `usuarios`(`id_u`) ON DELETE SET NULL;
ALTER TABLE `noticias` ADD CONSTRAINT IF NOT EXISTS `fk_noticias_editado_por` FOREIGN KEY (`editado_por`) REFERENCES `usuarios`(`id_u`) ON DELETE SET NULL;

-- 5. Tabla para tokens de recuperación de contraseña
CREATE TABLE IF NOT EXISTS `password_reset_tokens` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL UNIQUE,
  `tipo_usuario` enum('admin','lector') NOT NULL,
  `creado` timestamp NOT NULL DEFAULT current_timestamp(),
  `expira` timestamp NOT NULL,
  `usado` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_email_token` (`email`, `token`),
  INDEX `idx_expira` (`expira`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 6. Agregar columna de orden a categorías
ALTER TABLE `categorias` ADD COLUMN IF NOT EXISTS `orden` INT DEFAULT 0 AFTER `nombre`;

-- 7. Agregar columna de orden a videos (para drag & drop de reordenamiento)
ALTER TABLE `videos` ADD COLUMN IF NOT EXISTS `orden` INT DEFAULT 0 AFTER `activo`;

-- 8. Agregar columna slug para URLs amigables en noticias
ALTER TABLE `noticias` ADD COLUMN IF NOT EXISTS `slug` VARCHAR(255) DEFAULT NULL AFTER `titulo`;
ALTER TABLE `noticias` ADD INDEX IF NOT EXISTS `idx_slug` (`slug`);

-- 9. Tabla para los logos
CREATE TABLE IF NOT EXISTS `logos_marcas` (
    `id_logo`  INT          NOT NULL AUTO_INCREMENT,
    `imagen`   VARCHAR(255) NOT NULL,
    `nombre`   VARCHAR(150) NOT NULL DEFAULT '',
    `activo`   TINYINT(1)   NOT NULL DEFAULT 1,
    `creado`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id_logo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. Permite definir hasta cuándo se muestra un logo.
ALTER TABLE `logos_marcas`
    ADD COLUMN `fecha_expiracion` DATETIME NULL DEFAULT NULL AFTER `activo`;

-- 11. Orden de logos de marcas colaboradoras (drag & drop en paginas.php)
ALTER TABLE `logos_marcas` ADD COLUMN IF NOT EXISTS `orden` INT NOT NULL DEFAULT 0 AFTER `activo`;
SET @r := 0;
UPDATE `logos_marcas` SET `orden` = (@r := @r + 1) ORDER BY `creado` ASC;

-- 12. Calificación editorial de noticias (1-5 estrellas, asignada al crear/editar)
ALTER TABLE `noticias` ADD COLUMN IF NOT EXISTS `calificacion` TINYINT UNSIGNED DEFAULT NULL COMMENT '1-5 estrellas — calificación editorial';

-- 13. Agregar columna valor a la tabla secciones y setear default para videos
ALTER TABLE `secciones` ADD COLUMN IF NOT EXISTS `valor` VARCHAR(255) DEFAULT NULL;
UPDATE `secciones` SET `valor` = 'PLMC9KNkIncKvYin_USF1QeqG50KB1K1uD' WHERE `nombre` = 'videos' AND `valor` IS NULL;

-- 13. Columnas para el sistema de reseñas (Reviews)
ALTER TABLE `noticias`
ADD COLUMN IF NOT EXISTS `tipo_publicacion` ENUM('noticia', 'review') NOT NULL DEFAULT 'noticia' AFTER `id`,
ADD COLUMN IF NOT EXISTS `calificacion` DECIMAL(3,1) DEFAULT NULL AFTER `tipo_publicacion`,
ADD COLUMN IF NOT EXISTS `pros` TEXT DEFAULT NULL AFTER `calificacion`,
ADD COLUMN IF NOT EXISTS `contras` TEXT DEFAULT NULL AFTER `pros`;

-- 14. Columnas para próximos estrenos
ALTER TABLE `noticias`
ADD COLUMN IF NOT EXISTS `es_estreno` TINYINT(1) NOT NULL DEFAULT 0 AFTER `contras`,
ADD COLUMN IF NOT EXISTS `seccion_estreno` VARCHAR(50) DEFAULT NULL AFTER `es_estreno`;

-- 15. Imagen paisaje (21:9) — formato intermedio entre banner y miniatura, usado en cards destacadas
ALTER TABLE `noticias` ADD COLUMN IF NOT EXISTS `crop4` TEXT DEFAULT NULL COMMENT '21:9 paisaje — card destacada (estreno, reviews)';

-- 16. Orden de categorías por noticia (define qué categoría aparece primero en las tarjetas)
ALTER TABLE `noticia_categoria` ADD COLUMN IF NOT EXISTS `orden` TINYINT UNSIGNED NOT NULL DEFAULT 1;
UPDATE `noticia_categoria` nc
    JOIN (SELECT noticia_id, categoria_id, ROW_NUMBER() OVER (PARTITION BY noticia_id ORDER BY categoria_id ASC) AS rn FROM noticia_categoria) sub
    ON nc.noticia_id = sub.noticia_id AND nc.categoria_id = sub.categoria_id
    SET nc.orden = sub.rn;

-- 17. Sistema de baneo de usuarios (moderación por superadmin)
--     Aplica tanto a lectores (comentaristas) como a usuarios (admins/editores).
--     baneado_hasta = fecha de expiración del baneo temporal (NULL = sin baneo temporal)
--     baneado_permanente = 1 para suspensión indefinida
--     Un usuario está baneado si baneado_permanente = 1 O baneado_hasta > NOW()
ALTER TABLE `lectores`
  ADD COLUMN IF NOT EXISTS `baneado_hasta` DATETIME NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `baneado_permanente` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `baneado_motivo` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `usuarios`
  ADD COLUMN IF NOT EXISTS `baneado_hasta` DATETIME NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `baneado_permanente` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `baneado_motivo` VARCHAR(255) NULL DEFAULT NULL;

-- 18. Búsqueda rápida: Índice FULLTEXT para optimizar motor de búsqueda
-- (Si da error de duplicado en ejecución por ya estar creado, omitir)
ALTER TABLE `noticias` ADD FULLTEXT INDEX `idx_busqueda_rapida` (`titulo`, `descripcion`, `contenido`);

-- 19. Notificaciones a usuarios (avisos de moderación: suspensión / reactivación)
--     tipo_usuario + user_id apuntan a lectores.id o usuarios.id_u según corresponda.
CREATE TABLE IF NOT EXISTS `notificaciones` (
  `id_notificacion` int(11) NOT NULL AUTO_INCREMENT,
  `tipo_usuario` enum('lector','admin') NOT NULL,
  `user_id` int(11) NOT NULL,
  `tipo` varchar(40) NOT NULL DEFAULT 'general',
  `titulo` varchar(255) NOT NULL,

-- 20. Columna meta_json para campos configurables de páginas en CMS
ALTER TABLE `paginas` ADD COLUMN IF NOT EXISTS `meta_json` JSON DEFAULT NULL;
  `mensaje` text NOT NULL,
  `leida` tinyint(1) NOT NULL DEFAULT 0,
  `creada` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id_notificacion`),
  KEY `idx_notif_user` (`tipo_usuario`, `user_id`, `leida`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 20. Control global de comentarios (sección activa por defecto)
INSERT IGNORE INTO `secciones` (`nombre`, `estado`) VALUES ('comentarios', 1);

-- 21. Contador de intentos de profanidad para lectores (baneo automático)
ALTER TABLE `lectores` ADD COLUMN IF NOT EXISTS `intentos_profanos` INT DEFAULT 0 AFTER `avatar_id`;

-- 22. Columnas de baneo para lectores
ALTER TABLE `lectores` ADD COLUMN IF NOT EXISTS `baneado_hasta` DATETIME NULL DEFAULT NULL;
ALTER TABLE `lectores` ADD COLUMN IF NOT EXISTS `baneado_permanente` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `lectores` ADD COLUMN IF NOT EXISTS `baneado_motivo` VARCHAR(255) NULL DEFAULT NULL;

-- 23. Columnas de baneo para usuarios (administradores/editores)
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `baneado_hasta` DATETIME NULL DEFAULT NULL;
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `baneado_permanente` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `usuarios` ADD COLUMN IF NOT EXISTS `baneado_motivo` VARCHAR(255) NULL DEFAULT NULL;

-- 24. Crear la categoría 'Random'
INSERT IGNORE INTO `categorias` (`nombre`, `orden`) VALUES ('Random', 8);


-- 25. Vocabulario ofensivo completo (importación de palabras)
INSERT IGNORE INTO `filtro_diccionario` (`palabra_baneada`, `reemplazo`) VALUES
('a la verga', '***'),
('a tomar por culo', '***'),
('abanto', '***'),
('abombado', '***'),
('abrazafarolas', '***'),
('abstinencia', '***'),
('abusador', '***'),
('abuso', '***'),
('accidente cerebrovascular', '***'),
('ácido', '***'),
('acosador', '***'),
('acoso', '***'),
('acre', '***'),
('aculillao', '***'),
('adhd', '***'),
('adicción', '***'),
('adictivo', '***'),
('adufe', '***'),
('adulador', '***'),
('agacharsele el pico', '***'),
('agresivo', '***'),
('agrio', '***'),
('aguardiente', '***'),
('agueonao', '***'),
('aguevado', '***'),
('aguevao', '***'),
('ahueonao', '***'),
('ahuevado', '***'),
('ahuevonado', '***'),
('alcohol', '***'),
('alcornoque', '***'),
('alergia', '***'),
('alfenique', '***'),
('allergy', '***'),
('alucinando', '***'),
('alucinógeno', '***'),
('amargo', '***'),
('amarrete', '***'),
('amputación', '***'),
('amputation', '***'),
('anal', '***'),
('analfabeto', '***'),
('andar con la piedra o roca', '***'),
('andrajoso', '***'),
('andurriasmo', '***'),
('anfetamina', '***'),
('animal', '***'),
('ano', '***'),
('ansiedad', '***'),
('ansioso', '***'),
('anus', '***'),
('anxiety', '***'),
('apático', '***'),
('areola', '***'),
('arepa', '***'),
('arm', '***'),
('arma', '***'),
('arrastracueros', '***'),
('arrecha', '***'),
('arrechera', '***'),
('arrecho', '***'),
('arrimado', '***'),
('artaban', '***'),
('arteria', '***'),
('artery', '***'),
('asesinato', '***'),
('asexual', '***'),
('asma', '***'),
('asno', '***'),
('asqueroso', '***'),
('ass', '***'),
('asthma', '***'),
('atarre', '***'),
('atontado', '***'),
('atorrante', '***'),
('atrevido', '***'),
('autism', '***'),
('autismo', '***'),
('autodestructivo', '***'),
('aweonao', '***'),
('awevado', '***'),
('babieca', '***'),
('babieco', '***'),
('baboso', '***'),
('badulaque', '***'),
('bajo', '***'),
('balin', '***'),
('banano', '***'),
('barrabas', '***'),
('barriobajero', '***'),
('bastardo', '***'),
('basura', '***'),
('beastiality', '***'),
('bebecharcos', '***'),
('bebida alcohólica', '***'),
('bellaco', '***'),
('belloto', '***'),
('benign', '***'),
('benigno', '***'),
('berzotas', '***'),
('bestia', '***'),
('bestiality', '***'),
('besugo', '***'),
('bipolar', '***'),
('birlocha', '***'),
('bisexual', '***'),
('blandito', '***'),
('blood', '***'),
('blowjob', '***'),
('boba', '***'),
('bobalicon', '***'),
('bobo', '***'),
('boboleto', '***'),
('bobolicon', '***'),
('boca', '***'),
('boca abierta', '***'),
('bocabuzon', '***'),
('bocachancla', '***'),
('bocallanta', '***'),
('bochinche', '***'),
('bochinchudo', '***'),
('bodoque', '***'),
('bofe', '***'),
('bola', '***'),
('bolas', '***'),
('boleta', '***'),
('boletoso', '***'),
('bollo', '***'),
('bolsa', '***'),
('boludo', '***'),
('bomba', '***'),
('bombril', '***'),
('bone', '***'),
('boob', '***'),
('boquimuelle', '***'),
('borrachera', '***'),
('borracho', '***'),
('borrico', '***'),
('bostero', '***'),
('botarate', '***'),
('boton de cuero', '***'),
('boyo', '***'),
('brain', '***'),
('brandy', '***'),
('brasas', '***'),
('brazo', '***'),
('breast', '***'),
('bruto', '***'),
('bucefalo', '***'),
('buena mierda', '***'),
('buey', '***'),
('bufa', '***'),
('bufo', '***'),
('bulto', '***'),
('bultuntun', '***'),
('burlón', '***'),
('burro', '***'),
('butt', '***'),
('buttocks', '***'),
('cabeciduro', '***'),
('cabello', '***'),
('cabestro', '***'),
('cabeza', '***'),
('cabeza de guevo', '***'),
('cabeza de machete', '***'),
('cabeza de ponque', '***'),
('cabeza de verga', '***'),
('cabezaalberca', '***'),
('cabezabuque', '***'),
('cabezota', '***'),
('cabilla', '***'),
('cabro', '***'),
('cabrón', '***'),
('cabrona', '***'),
('caca', '***'),
('cacaso', '***'),
('cachapera', '***'),
('cachibache', '***'),
('cachon', '***'),
('cachorro', '***'),
('cachudo', '***'),
('cacorra', '***'),
('cacorro', '***'),
('cafe en las bolas', '***'),
('cafre', '***'),
('cagalindes', '***'),
('cagalitroso', '***'),
('cagapalo', '***'),
('cagar', '***'),
('cagarla', '***'),
('cagarruta', '***'),
('cagarse', '***'),
('cagarte', '***'),
('cago', '***'),
('cagon', '***'),
('cagon de mierda', '***'),
('cagona', '***'),
('caido del zarzo', '***'),
('cajeta', '***'),
('calabaza', '***'),
('calambuco', '***'),
('calamidad', '***'),
('calduo', '***'),
('caliche', '***'),
('calienta guevo', '***'),
('calientahielos', '***'),
('caligueva', '***'),
('calzamonas', '***'),
('camba', '***'),
('camionero', '***'),
('caña', '***'),
('canalla', '***'),
('canazo', '***'),
('cáncer', '***'),
('cangrejera', '***'),
('canibalismo', '***'),
('cannibalism', '***'),
('cansalmas', '***'),
('cantamananas', '***'),
('canuto', '***'),
('capilar', '***'),
('capillary', '***'),
('capot de volkswagen', '***'),
('capotiar', '***'),
('capullo', '***'),
('cara', '***'),
('cara de cojudo', '***'),
('cara de mierda', '***'),
('cara de pepa', '***'),
('cara de pija', '***'),
('cara de tabla', '***'),
('cara de verga', '***'),
('cara e feto', '***'),
('caracaballo', '***'),
('caracarton', '***'),
('caraculo', '***'),
('caraenalga', '***'),
('caraepeo', '***'),
('caraflema', '***'),
('caraja', '***'),
('carajaula', '***'),
('carajo', '***'),
('carajote', '***'),
('carapapa', '***'),
('carapijo', '***'),
('carcunda', '***'),
('care chimba', '***'),
('care gorro', '***'),
('care monda', '***'),
('care pepa', '***'),
('care picha', '***'),
('care pija', '***'),
('care pinga', '***'),
('care verga', '***'),
('carebarro', '***'),
('caremonda', '***'),
('caremuerto', '***'),
('careperro', '***'),
('carepi', '***'),
('caretiesto', '***'),
('careverga', '***'),
('cargar', '***'),
('carne con papas', '***'),
('carnicero', '***'),
('carteluo', '***'),
('catacaldos', '***'),
('cáustico', '***'),
('cazurro', '***'),
('cebillo', '***'),
('cebilluo', '***'),
('cebollino', '***'),
('ceguegue', '***'),
('ceja', '***'),
('cenizo', '***'),
('cenutrio', '***'),
('ceporro', '***'),
('cerdo', '***'),
('cerebro', '***'),
('cernicalo', '***'),
('cerote', '***'),
('cerveza', '***'),
('cerveza artesanal', '***'),
('champagne', '***'),
('charran', '***'),
('chavista', '***'),
('chemotherapy', '***'),
('cherna', '***'),
('chicha', '***'),
('chichar', '***'),
('child abuse', '***'),
('child exploitation', '***'),
('child porn', '***'),
('chimar', '***'),
('chimbo', '***'),
('chinga', '***'),
('chinga su madre', '***'),
('chingada', '***'),
('chingadera', '***'),
('chingado', '***'),
('chingando', '***'),
('chingar', '***'),
('chingo', '***'),
('chingona', '***'),
('chingoneria', '***'),
('chiquilicuatre', '***'),
('chirimbaina', '***'),
('chisgarabis', '***'),
('cho', '***'),
('cho de la gran puta', '***'),
('chocha', '***'),
('chocho', '***'),
('chola', '***'),
('chola e burro', '***'),
('choro', '***'),
('chorra', '***'),
('chota', '***'),
('choto', '***'),
('chucha', '***'),
('chucha e culo', '***'),
('chuchesumadre', '***'),
('chuchita', '***'),
('chulo', '***'),
('chunchurria', '***'),
('chupa culo', '***'),
('chupacables', '***'),
('chupame la raja', '***'),
('chupapija', '***'),
('chupapinga', '***'),
('chupasangre', '***'),
('chupe verga', '***'),
('chupelo', '***'),
('chupeme la picha', '***'),
('chupoptero', '***'),
('churre', '***'),
('churri', '***'),
('chusma', '***'),
('chuta', '***'),
('cierrabares', '***'),
('cipote', '***'),
('cirugía', '***'),
('clitoris', '***'),
('cocaína', '***'),
('cochesumadre', '***'),
('cochina', '***'),
('cochino', '***'),
('cochon', '***'),
('cock', '***'),
('cocolla', '***'),
('codo', '***'),
('coger', '***'),
('coje culo', '***'),
('cojeculo', '***'),
('cojer', '***'),
('cojio', '***'),
('cojonera', '***'),
('cojones', '***'),
('cojonudo', '***'),
('cojudo', '***'),
('colla', '***'),
('collera', '***'),
('colocado', '***'),
('columna vertebral', '***'),
('coma mierda', '***'),
('come chicle', '***'),
('come huevo', '***'),
('come mierda', '***'),
('come moco', '***'),
('comebolsas', '***'),
('comechapas', '***'),
('comeflores', '***'),
('comegato', '***'),
('comemierda', '***'),
('comestacas', '***'),
('compulsivo', '***'),
('coñac', '***'),
('conaso', '***'),
('conaza', '***'),
('conazo', '***'),
('concha', '***'),
('concha de tu madre', '***'),
('conchatumare', '***'),
('conchesumare', '***'),
('conchetumadre', '***'),
('confianza de perro', '***'),
('conito', '***'),
('coño', '***'),
('cono de madre', '***'),
('cono de tu pepa', '***'),
('contumaz', '***'),
('convulsión', '***'),
('coprofago', '***'),
('corazón', '***'),
('cortante', '***'),
('covero', '***'),
('coviao', '***'),
('cp', '***'),
('craputoso', '***'),
('cresta', '***'),
('cretino', '***'),
('cruda', '***'),
('csam', '***'),
('cuaima', '***'),
('cuatriboliao', '***'),
('cuca', '***'),
('cucaracha', '***'),
('cuchara', '***'),
('cuchillo', '***'),
('cueca', '***'),
('cueco', '***'),
('cuecon', '***'),
('cuello', '***'),
('cuero', '***'),
('cuerpoescombro', '***'),
('cuervo', '***'),
('cuita', '***'),
('cuite', '***'),
('culantro', '***'),
('cule', '***'),
('culeado', '***'),
('culeao', '***'),
('culear', '***'),
('culebra', '***'),
('culero', '***'),
('culia', '***'),
('culiabierto', '***'),
('culiao', '***'),
('culiar', '***'),
('culillo', '***'),
('culilluo', '***'),
('culo', '***'),
('culopollo', '***'),
('cum', '***'),
('cunnilingus', '***'),
('cunt', '***'),
('cunumi', '***'),
('curda', '***'),
('curdo', '***'),
('currutaca', '***'),
('cursalera', '***'),
('da asco', '***'),
('dar por culo', '***'),
('de balde', '***'),
('de pinga', '***'),
('dedo', '***'),
('dedo del pie', '***'),
('degenerado', '***'),
('degradante', '***'),
('delputas', '***'),
('demencia', '***'),
('demente', '***'),
('dementia', '***'),
('demisexual', '***'),
('denigrante', '***'),
('dependencia', '***'),
('depresión', '***'),
('depresivo', '***'),
('depression', '***'),
('desahuevate', '***'),
('desatento', '***'),
('descarado', '***'),
('descarao', '***'),
('descerebrado', '***'),
('descontrolado', '***'),
('descuidado', '***'),
('desgarracalzas', '***'),
('desgraciada', '***'),
('desgraciado', '***'),
('desobediente', '***'),
('desorejada', '***'),
('desorejado', '***'),
('despectivo', '***'),
('destilado', '***'),
('destructivo', '***'),
('diarrea', '***'),
('diarrhea', '***'),
('dick', '***'),
('diente', '***'),
('dientes', '***'),
('disability', '***'),
('discalculia', '***'),
('discapacidad', '***'),
('disease', '***'),
('disgrafía', '***'),
('dislexia', '***'),
('disoluto', '***'),
('distraído', '***'),
('DMT', '***'),
('doble hijueputa', '***'),
('doblehijueputa', '***'),
('dolencia', '***'),
('dondiego', '***'),
('donnadie', '***'),
('droga', '***'),
('drogado', '***'),
('drogo', '***'),
('dundo', '***'),
('dyscalculia', '***'),
('dysgraphia', '***'),
('dyslexia', '***'),
('ear', '***'),
('ebrio', '***'),
('echacantos', '***'),
('ejaculation', '***'),
('ejarramantas', '***'),
('embriagante', '***'),
('embriaguez', '***'),
('en otro mundo', '***'),
('enchavar', '***'),
('energumeno', '***'),
('enfermedad', '***'),
('enganapichanga', '***'),
('envenenamiento', '***'),
('epilepsia', '***'),
('epilepsy', '***'),
('erg', '***'),
('erga', '***'),
('esbaratabailes', '***'),
('esbirro', '***'),
('escolimoso', '***'),
('escornacabras', '***'),
('escualido', '***'),
('espumante', '***'),
('espundia', '***'),
('esputo', '***'),
('esquizofrenia', '***'),
('esquizofrénico', '***'),
('estolido', '***'),
('estómago', '***'),
('estulto', '***'),
('estupefaciente', '***'),
('estúpido', '***'),
('excrement', '***'),
('excremento', '***'),
('explosivo', '***'),
('éxtasis', '***'),
('extremista', '***'),
('eyaculación', '***'),
('eye', '***'),
('eyebrow', '***'),
('eyelash', '***'),
('face', '***'),
('facilota', '***'),
('facineroso', '***'),
('fanático', '***'),
('fanfosquero', '***'),
('fantoche', '***'),
('fariseo', '***'),
('fat', '***'),
('fecal', '***'),
('feces', '***'),
('federico', '***'),
('fellatio', '***'),
('felon', '***'),
('felona', '***'),
('fermentado', '***'),
('feyuco', '***'),
('filimincias', '***'),
('finger', '***'),
('flasheando', '***'),
('flete', '***'),
('fletera', '***'),
('flojo', '***'),
('foligoso', '***'),
('follada', '***'),
('follar', '***'),
('folle', '***'),
('follen', '***'),
('follona', '***'),
('foot', '***'),
('forro', '***'),
('forro de caballo', '***'),
('freson', '***'),
('fuera de sí', '***'),
('fulastre', '***'),
('fumado', '***'),
('fumeque', '***'),
('fumon', '***'),
('fundillo', '***'),
('fungus', '***'),
('furby', '***'),
('gallina', '***'),
('gamberra', '***'),
('ganan', '***'),
('ganapan', '***'),
('ganapio', '***'),
('gandul', '***'),
('ganso', '***'),
('garbimba', '***'),
('garrancha', '***'),
('garrancho', '***'),
('garrote', '***'),
('gatorade', '***'),
('gaver', '***'),
('gay', '***'),
('gaznapiro', '***'),
('genocidio', '***'),
('geva', '***'),
('GHB', '***'),
('gil', '***'),
('gilipollas', '***'),
('gilipuertas', '***'),
('ginebra', '***'),
('giraesquinas', '***'),
('gocho', '***'),
('golfa', '***'),
('golpe de ala', '***'),
('gonorrea', '***'),
('gore', '***'),
('gorrero', '***'),
('gorrino', '***'),
('gorron', '***'),
('gorrumino', '***'),
('gran doble hijueputa', '***'),
('gran puta', '***'),
('granizo', '***'),
('grantriplehijueputa', '***'),
('grasa', '***'),
('grosero', '***'),
('guarayo', '***'),
('guate', '***'),
('guebon', '***'),
('gueleguele', '***'),
('guevazo', '***'),
('guevon', '***'),
('guevona', '***'),
('guiso', '***'),
('guitarro', '***'),
('gurriato', '***'),
('gurrupleta', '***'),
('gurrupleto', '***'),
('habahela', '***'),
('hacha', '***'),
('hair', '***'),
('hala bola', '***'),
('hand', '***'),
('handicap', '***'),
('head', '***'),
('heart', '***'),
('heces', '***'),
('heroína', '***'),
('heterosexual', '***'),
('hígado', '***'),
('hija de puta', '***'),
('hijaeputa', '***'),
('hijo de diablo', '***'),
('hijo de la gran flauta', '***'),
('hijo de la gran puta', '***'),
('hijo de la perra', '***'),
('hijo de las siete leches', '***'),
('hijo de perra', '***'),
('hijo de puta', '***'),
('hijoeputa', '***'),
('hijuefruta', '***'),
('hijuelaverga', '***'),
('hijueperra', '***'),
('hijueputa', '***'),
('hipertensión', '***'),
('hipocrita', '***'),
('hipotensión', '***'),
('hiriente', '***'),
('holocausto', '***'),
('hombro', '***'),
('homicidio', '***'),
('hominicaca', '***'),
('hominicaco', '***'),
('homosexual', '***'),
('hongo', '***'),
('hostia', '***'),
('hoyo', '***'),
('hoyuda', '***'),
('hueco', '***'),
('huele huele', '***'),
('huele vicho', '***'),
('huelegateras', '***'),
('hueon', '***'),
('hueso', '***'),
('huevada', '***'),
('hueveo', '***'),
('huevo', '***'),
('huevon', '***'),
('huevona', '***'),
('huevonada', '***'),
('humillante', '***'),
('hypertension', '***'),
('hypotension', '***'),
('idiota', '***'),
('illness', '***'),
('imbécil', '***'),
('imilla', '***'),
('immune system', '***'),
('impasible', '***'),
('impulsivo', '***'),
('inamovible', '***'),
('incest', '***'),
('incesto', '***'),
('inconmovible', '***'),
('incrospido', '***'),
('indiferente', '***'),
('indio', '***'),
('infección', '***'),
('infection', '***'),
('inflador', '***'),
('inflexible', '***'),
('ingnorante', '***'),
('inmundo', '***'),
('insolente', '***'),
('insubordinado', '***'),
('insultante', '***'),
('intestine', '***'),
('intestino', '***'),
('intoxicación', '***'),
('intoxicado', '***'),
('intoxicante', '***'),
('intransigente', '***'),
('irónico', '***'),
('irrespetuoso', '***'),
('jaime', '***'),
('jala bola', '***'),
('jalla', '***'),
('jallo', '***'),
('jambeco', '***'),
('jartera', '***'),
('jeva', '***'),
('jinetera', '***'),
('joder', '***'),
('joputa', '***'),
('joto', '***'),
('jueputa', '***'),
('jugado de cegua', '***'),
('kara', '***'),
('ketamina', '***'),
('kidney', '***'),
('kilua', '***'),
('la concha de la lora', '***'),
('la penca del burro', '***'),
('labios', '***'),
('ladilla', '***'),
('ladillaa', '***'),
('ladillao', '***'),
('lambetuerca', '***'),
('lambevicho', '***'),
('lambon', '***'),
('lambusia', '***'),
('lamecharcos', '***'),
('lameculo', '***'),
('lameculos', '***'),
('lameplatos', '***'),
('lampara', '***'),
('lamparoso', '***'),
('lary', '***'),
('lechugino', '***'),
('lechuguin', '***'),
('lechuguino', '***'),
('leg', '***'),
('lelo', '***'),
('lengua', '***'),
('lengua en el estuche', '***'),
('leproso', '***'),
('lerdo', '***'),
('lesbiana', '***'),
('lichigo', '***'),
('licor', '***'),
('linfa', '***'),
('lips', '***'),
('liver', '***'),
('llaga', '***'),
('llamon', '***'),
('llamona', '***'),
('llokalla', '***'),
('loba', '***'),
('loca', '***'),
('loco', '***'),
('loco de mierda', '***'),
('locota', '***'),
('loli', '***'),
('lolita', '***'),
('LSD', '***'),
('lung', '***'),
('luser', '***'),
('lymph', '***'),
('macaco', '***'),
('macana', '***'),
('machete', '***'),
('macheterico', '***'),
('maduro', '***'),
('maestro parcha', '***'),
('magapa', '***'),
('maje', '***'),
('majunche', '***'),
('mal aliento', '***'),
('mal cogida', '***'),
('mala hoja', '***'),
('malagente', '***'),
('malandra', '***'),
('malandro', '***'),
('maldicienta', '***'),
('maldiciento', '***'),
('maldita', '***'),
('maldita rata', '***'),
('malfollao', '***'),
('malignant', '***'),
('maligno', '***'),
('mallen', '***'),
('malparia', '***'),
('malparida', '***'),
('malparido', '***'),
('malpario', '***'),
('maltrato', '***'),
('mama culo', '***'),
('mama huevo', '***'),
('mama picha', '***'),
('mama vicho', '***'),
('mamacallos', '***'),
('mamada pbc', '***'),
('mamador de paloma,', '***'),
('mamagueva', '***'),
('mamagueveteo', '***'),
('mamaguevo', '***'),
('mamao', '***'),
('mamarracha', '***'),
('mamarracho', '***'),
('mamavicho', '***'),
('mamelo', '***'),
('mamera', '***'),
('mamon', '***'),
('mandao', '***'),
('manguarrian', '***'),
('mano', '***'),
('manuela', '***'),
('maraco', '***'),
('marica', '***'),
('marico', '***'),
('marico preso', '***'),
('marico triste', '***'),
('maricón', '***'),
('mariconzon', '***'),
('mariflor', '***'),
('marihuana', '***'),
('marihuanero', '***'),
('marimacho', '***'),
('mariquita', '***'),
('marperio', '***'),
('marrana', '***'),
('marrano', '***'),
('martillo', '***'),
('maseta', '***'),
('masturbación', '***'),
('masturbarse', '***'),
('masturbate', '***'),
('masturbation', '***'),
('matosurrero', '***'),
('me cago en su madre', '***'),
('me llegas al pincho', '***'),
('me pelas la pija', '***'),
('me vale verga', '***'),
('meapilas', '***'),
('meason', '***'),
('mecaniquito', '***'),
('médula espinal', '***'),
('menopausica', '***'),
('menso', '***'),
('menstruación', '***'),
('menstrual', '***'),
('mentirosa', '***'),
('mentiroso', '***'),
('mercachifle', '***'),
('metanfetamina', '***'),
('metelo', '***'),
('metomentodo', '***'),
('metralleta', '***'),
('mezcal', '***'),
('mezquino', '***'),
('mica', '***'),
('micha', '***'),
('michita', '***'),
('mico', '***'),
('microondas', '***'),
('mierda', '***'),
('mierdoza', '***'),
('mierdozo', '***'),
('minusvalía', '***'),
('mio', '***'),
('misera', '***'),
('moclin', '***'),
('moco', '***'),
('mogólico', '***'),
('moja’ el picure', '***'),
('mojonero', '***'),
('monda', '***'),
('mongol', '***'),
('mongolico', '***'),
('mongolo', '***'),
('moquito', '***'),
('mordaz', '***'),
('morlaco', '***'),
('moromierda', '***'),
('morronga', '***'),
('mostro', '***'),
('mota', '***'),
('mouth', '***'),
('muerdealmohada', '***'),
('muergana', '***'),
('muergano', '***'),
('mula', '***'),
('muscle', '***'),
('músculo', '***'),
('muslo', '***'),
('mutilación', '***'),
('mutilation', '***'),
('nabo', '***'),
('nalga', '***'),
('narcótico', '***'),
('nariz', '***'),
('nauseabundo', '***'),
('navaja', '***'),
('nazi', '***'),
('neck', '***'),
('necrofilia', '***'),
('necrophilia', '***'),
('negligente', '***'),
('negro', '***'),
('neja', '***'),
('nejo', '***'),
('nengue', '***'),
('nera', '***'),
('nero', '***'),
('nerve', '***'),
('nervio', '***'),
('nica', '***'),
('niche', '***'),
('nipple', '***'),
('no jodas', '***'),
('no sirves pa ni mierda', '***'),
('nojo', '***'),
('nojoda', '***'),
('nona', '***'),
('noneco', '***'),
('nono', '***'),
('nose', '***'),
('obesidad', '***'),
('obesity', '***'),
('obsesivo', '***'),
('obstinado', '***'),
('ocote', '***'),
('ofensivo', '***'),
('oído', '***'),
('ojete', '***'),
('ojo', '***'),
('olluo', '***'),
('ordinario', '***'),
('organ', '***'),
('órgano', '***'),
('orgasm', '***'),
('orgasmo', '***'),
('orina', '***'),
('ortiva', '***'),
('orto', '***'),
('ostia', '***'),
('pacharro', '***'),
('paco', '***'),
('pacucuso', '***'),
('pacufo', '***'),
('pacuso', '***'),
('pacusobo', '***'),
('paga peo', '***'),
('paga prote', '***'),
('pagafantas', '***'),
('paja', '***'),
('pajaro', '***'),
('pajaron', '***'),
('pajero', '***'),
('pajizo', '***'),
('pajua', '***'),
('pajuo', '***'),
('pajuso', '***'),
('palo', '***'),
('paloma', '***'),
('panal caga’o', '***'),
('pandorga', '***'),
('panocha', '***'),
('pansexual', '***'),
('papaya', '***'),
('papo', '***'),
('parálisis', '***'),
('paralysis', '***'),
('paranoico', '***'),
('parasite', '***'),
('parásito', '***'),
('parcha', '***'),
('parchita', '***'),
('pargo', '***'),
('pargula', '***'),
('parido por el sobaco', '***'),
('pasado', '***'),
('pasmado', '***'),
('pastelero', '***'),
('pastrulo', '***'),
('pata e’ rolo', '***'),
('patear el tobo', '***'),
('pato', '***'),
('payaso', '***'),
('pea', '***'),
('pecho', '***'),
('pecuso', '***'),
('pedazo de mierda', '***'),
('pedo', '***'),
('pedofilia', '***'),
('pedofilo', '***'),
('pedophile', '***'),
('pee', '***'),
('pegoste de olla', '***'),
('peinabombillas', '***'),
('pelele', '***'),
('pelotas', '***'),
('pelotudo', '***'),
('penco', '***'),
('pencon', '***'),
('pendeja', '***'),
('pendejo', '***'),
('pene', '***'),
('penis', '***'),
('peo', '***'),
('pepa del culo', '***'),
('pepita', '***'),
('perillaoriental', '***'),
('period', '***'),
('perra', '***'),
('perro', '***'),
('perro e’ quinta', '***'),
('perro e’ rancho', '***'),
('perroflauta', '***'),
('pervertido', '***'),
('pestaña', '***'),
('pete', '***'),
('petimetre', '***'),
('petizo', '***'),
('pezcao', '***'),
('pezón', '***'),
('picador', '***'),
('picha', '***'),
('pichicosa', '***'),
('pichinga', '***'),
('pichon de cabron', '***'),
('pichurria', '***'),
('pico', '***'),
('pie', '***'),
('pie de atleta', '***'),
('piel', '***'),
('pierna', '***'),
('pija', '***'),
('pijotero', '***'),
('pincharrata', '***'),
('pinche', '***'),
('pinga', '***'),
('pingo', '***'),
('pipian', '***'),
('pirinola', '***'),
('piripicho', '***'),
('piroba', '***'),
('pirobo', '***'),
('piruja', '***'),
('pisa', '***'),
('pisa huevos', '***'),
('pisa ninas', '***'),
('pisco', '***'),
('piss', '***'),
('pistola', '***'),
('pitillo', '***'),
('plaga', '***'),
('plasta', '***'),
('playo', '***'),
('plegocha', '***'),
('pocha', '***'),
('polla', '***'),
('pollerudo', '***'),
('poluta', '***'),
('poluto', '***'),
('polvo del gallo', '***'),
('polvo del kerosene', '***'),
('pordiosero', '***'),
('porqueria', '***'),
('porton de iglesia', '***'),
('poto', '***'),
('primo', '***'),
('procaz', '***'),
('próstata', '***'),
('prostate', '***'),
('prosti', '***'),
('prostituta', '***'),
('psicoactivo', '***'),
('psicosis', '***'),
('psicótico', '***'),
('psilocibina', '***'),
('psychosis', '***'),
('pucha', '***'),
('puchica', '***'),
('puerco', '***'),
('puke', '***'),
('pullar', '***'),
('pullon', '***'),
('pulmón', '***'),
('pulque', '***'),
('puneta', '***'),
('punzante', '***'),
('pupu', '***'),
('purruja', '***'),
('pussy', '***'),
('puta', '***'),
('puta madre', '***'),
('putas', '***'),
('puto', '***'),
('putona', '***'),
('puya', '***'),
('quemero', '***'),
('querrequerre', '***'),
('queso', '***'),
('quesua', '***'),
('quesuo', '***'),
('quimioterapia', '***'),
('racamofin', '***'),
('radiación', '***'),
('radiation', '***'),
('radical', '***'),
('raja', '***'),
('rajunarepa', '***'),
('ramera', '***'),
('rape', '***'),
('rata', '***'),
('ratica', '***'),
('realengo', '***'),
('rebelde', '***'),
('recochesumadre', '***'),
('reconchesumare', '***'),
('reconchetumadre', '***'),
('recontra cono’e madre', '***'),
('recontraconisimo', '***'),
('recontraputa', '***'),
('recto', '***'),
('rectum', '***'),
('redoblona', '***'),
('refractario', '***'),
('regla', '***'),
('relambe guevo', '***'),
('relambechupaverga', '***'),
('relambepipe', '***'),
('remojar el cochayuyo', '***'),
('repipi', '***'),
('repugnante', '***'),
('reputa', '***'),
('reputisima', '***'),
('resaca', '***'),
('retrasado', '***'),
('revolucionario', '***'),
('ridi', '***'),
('ridiculo', '***'),
('rifle', '***'),
('riñón', '***'),
('rodaja de pina', '***'),
('rohypnol', '***'),
('rolitranco', '***'),
('ron', '***'),
('rosalada', '***'),
('rosquete', '***'),
('rozar las pelotas', '***'),
('ruchar', '***'),
('ruin', '***'),
('sabolo', '***'),
('saideliu', '***'),
('sake', '***'),
('salvaje', '***'),
('sambumbia', '***'),
('samo', '***'),
('sanaco', '***'),
('sangre', '***'),
('sapa', '***'),
('sapiosexual', '***'),
('sapo', '***'),
('sapo hijueputa', '***'),
('sarcástico', '***'),
('scat', '***'),
('schizophrenia', '***'),
('sebuda', '***'),
('sebudo', '***'),
('seizure', '***'),
('semen', '***'),
('serrana', '***'),
('serrano', '***'),
('serruchar', '***'),
('shota', '***'),
('shotacon', '***'),
('shoulder', '***'),
('si como ronca duerma', '***'),
('sickness', '***'),
('sidra', '***'),
('sieso', '***'),
('simeloma', '***'),
('sin cojones', '***'),
('sistema inmunológico', '***'),
('skin', '***'),
('snuff', '***'),
('sobraa', '***'),
('sobrao', '***'),
('sobredosis', '***'),
('socabron', '***'),
('sodomita', '***'),
('soez', '***'),
('somamao', '***'),
('sonzo', '***'),
('sopendejo', '***'),
('sopla condon', '***'),
('soplar el bisteck', '***'),
('soplon', '***'),
('sórdido', '***'),
('spinal cord', '***'),
('spine', '***'),
('stomach', '***'),
('stroke', '***'),
('su madre', '***'),
('subnormal', '***'),
('subversivo', '***'),
('sucio', '***'),
('suicida', '***'),
('suicidio', '***'),
('surgery', '***'),
('tacazo', '***'),
('tajante', '***'),
('tara', '***'),
('tarado', '***'),
('taraila', '***'),
('tarao', '***'),
('tarupido', '***'),
('tatengue', '***'),
('tavy', '***'),
('tdah', '***'),
('teeth', '***'),
('temiga', '***'),
('temigoso', '***'),
('temigue', '***'),
('tenso', '***'),
('tequila', '***'),
('terco', '***'),
('terrorismo', '***'),
('terruco', '***'),
('teta', '***'),
('tetas', '***'),
('thigh', '***'),
('tierruo', '***'),
('timbal', '***'),
('tirador', '***'),
('tirar', '***'),
('tirilla', '***'),
('tit', '***'),
('tiuque', '***'),
('tocapelotas', '***'),
('toche', '***'),
('toe', '***'),
('tongue', '***'),
('tontarron', '***'),
('tonto', '***'),
('tooth', '***'),
('topar', '***'),
('tortillera', '***'),
('tortura', '***'),
('torture', '***'),
('toto', '***'),
('totona', '***'),
('tozudo', '***'),
('traga sable', '***'),
('tragaleche', '***'),
('tragasable', '***'),
('trampolindebuchevergaoriental', '***'),
('tranca', '***'),
('trancado', '***'),
('transexual', '***'),
('trasero', '***'),
('trastanuta', '***'),
('travesti', '***'),
('trimardito', '***'),
('tripado', '***'),
('tripero', '***'),
('triplehijueputa', '***'),
('trolo', '***'),
('tu madre', '***'),
('tu taa loco', '***'),
('tufo', '***'),
('tuki', '***'),
('tunco', '***'),
('tusa', '***'),
('tutifruto', '***'),
('urine', '***'),
('uyuyuy', '***'),
('vagina', '***'),
('vaina', '***'),
('vale picha', '***'),
('vasito de agua', '***'),
('vein', '***'),
('vejatorio', '***'),
('vena', '***'),
('venado', '***'),
('venatica', '***'),
('venatico', '***'),
('veneno', '***'),
('verano', '***'),
('verdugo', '***'),
('verga', '***'),
('vergacion', '***'),
('vergatario', '***'),
('verraco', '***'),
('verriondo', '***'),
('vete a la chingada', '***'),
('veterano', '***'),
('viajando', '***'),
('vicho', '***'),
('vino', '***'),
('violación', '***'),
('violador', '***'),
('violento', '***'),
('violin', '***'),
('virus', '***'),
('vodka', '***'),
('volado', '***'),
('volar papagallo', '***'),
('vomit', '***'),
('vómito', '***'),
('vuerga', '***'),
('vulgar', '***'),
('vulgata', '***'),
('vulva', '***'),
('webon', '***'),
('webonauta', '***'),
('weon', '***'),
('wepota', '***'),
('whisky', '***'),
('wircha', '***'),
('wircho', '***'),
('wiro', '***'),
('wueon', '***'),
('xonga', '***'),
('xongo', '***'),
('yoyo', '***'),
('zamarro', '***'),
('zamuro', '***'),
('zascandil', '***'),
('zingar', '***'),
('zoofilia', '***'),
('zoofilo', '***'),
('zoophilia', '***'),
('zoquete', '***'),
('zorimba', '***'),
('zorimbo', '***'),
('zorra', '***'),
('zorritone', '***'),
('zorro', '***'),
('zorrupia', '***'),
('zunga', '***'),
('zurdo', '***'),
('zurumbatico', '***');

-- 69. Columnas para el sistema de verificación de correo de lectores
ALTER TABLE `lectores` ADD COLUMN IF NOT EXISTS `verificado` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `lectores` ADD COLUMN IF NOT EXISTS `token_verificacion` VARCHAR(100) NULL DEFAULT NULL;

-- 70. Icono y visibilidad en el menú para cada categoría (gestionado en views/cats.php)
--     icono        = clase de Bootstrap Icons (catálogo en views/helpers/iconos_categorias.php)
--     visible_menu = 0 oculta la categoría del menú hamburguesa y del desplegable de
--                    escritorio. La categoría sigue existiendo y su página /categoria/x
--                    sigue siendo accesible; solo desaparece de la navegación.
ALTER TABLE `categorias` ADD COLUMN IF NOT EXISTS `icono` VARCHAR(64) NOT NULL DEFAULT 'bi-tag-fill' AFTER `nombre`;
ALTER TABLE `categorias` ADD COLUMN IF NOT EXISTS `visible_menu` TINYINT(1) NOT NULL DEFAULT 1 AFTER `icono`;

-- Iconos iniciales para las categorías que ya existen. El WHERE sobre el valor
-- por defecto evita pisar cualquier icono que el admin ya haya elegido a mano.
UPDATE `categorias` SET `icono` = 'bi-film'              WHERE `nombre` = 'cine'        AND `icono` = 'bi-tag-fill';
UPDATE `categorias` SET `icono` = 'bi-stars'             WHERE `nombre` = 'anime'       AND `icono` = 'bi-tag-fill';
UPDATE `categorias` SET `icono` = 'bi-camera-reels-fill' WHERE `nombre` = 'peliculas'   AND `icono` = 'bi-tag-fill';
UPDATE `categorias` SET `icono` = 'bi-star-fill'         WHERE `nombre` = 'reviews'     AND `icono` = 'bi-tag-fill';
UPDATE `categorias` SET `icono` = 'bi-tv-fill'           WHERE `nombre` = 'series'      AND `icono` = 'bi-tag-fill';
UPDATE `categorias` SET `icono` = 'bi-cpu-fill'          WHERE `nombre` = 'tecnologia'  AND `icono` = 'bi-tag-fill';
UPDATE `categorias` SET `icono` = 'bi-controller'        WHERE `nombre` = 'videojuegos' AND `icono` = 'bi-tag-fill';
UPDATE `categorias` SET `icono` = 'bi-shuffle'           WHERE `nombre` = 'Random'      AND `icono` = 'bi-tag-fill';
